# Tools

In [1]:
from utils.tools import (
    # basic data
    get_participation_factor,
    get_current_power_consumption,
    get_current_power_generation,
    get_community_consumption,
    get_community_generation,
    get_measured_energy,
    # operations
    get_statistical_value,
    add_timeseries,
    subtract_timeseries,
    multiply_timeseries,
    divide_timeseries,
    min_timeseries,
    max_timeseries,
    # create_energy_plot,
    # diviated data
    calculate_community_potential,
    calculate_community_coverage,
    calculate_weighted_measured_energy
)

In [2]:
consumption_1 = get_community_consumption("2025-01-01 00:00", "2025-01-01 00:30")
consumption_2 = get_community_consumption("2025-01-01 00:00", "2025-01-01 00:30")
print(consumption_1)
print(consumption_2)

                        kwh
timestamp
2025-01-01 00:00:00  11.394
2025-01-01 00:15:00   5.250
                        kwh
timestamp
2025-01-01 00:00:00  11.394
2025-01-01 00:15:00   5.250

In [8]:
get_statistical_value("max", consumption_1)

11.394

In [7]:
add_timeseries([consumption_1, consumption_2])

                        kwh
timestamp
2025-01-01 00:00:00  22.788
2025-01-01 00:15:00  10.500

In [9]:
subtract_timeseries(minuend=consumption_1, subtrahend=consumption_2)

                     kwh
timestamp
2025-01-01 00:00:00  0.0
2025-01-01 00:15:00  0.0

In [10]:
multiply_timeseries(consumption_1, 2)

                        kwh
timestamp
2025-01-01 00:00:00  22.788
2025-01-01 00:15:00  10.500

In [11]:
divide_timeseries(consumption_1, 2)

                       kwh
timestamp
2025-01-01 00:00:00  5.697
2025-01-01 00:15:00  2.625

In [5]:
max_timeseries([consumption_1, consumption_2])

                        kwh
timestamp
2025-01-01 00:00:00  11.394
2025-01-01 00:15:00   5.250