In [3]:
import pandas as pd
from utils.files import load_xlsx
from utils.evaluation import adapt_evaluation_df

In [ ]:
# add runtime_seconds and token

In [4]:
df = load_xlsx("output/evaluation/evaluation.xlsx")
df = adapt_evaluation_df(df)
df

                   task_type  task_id  ... efficient    error
0       Direkte Datenabfrage        1  ...         1      NaN
1       Direkte Datenabfrage        1  ...         1      NaN
2       Direkte Datenabfrage        1  ...         1      NaN
3       Direkte Datenabfrage        1  ...         1      NaN
4       Direkte Datenabfrage        1  ...         1      NaN
..                       ...      ...  ...       ...      ...
805  Mehrquellenverarbeitung       90  ...         0  timeout
806  Mehrquellenverarbeitung       90  ...         0      NaN
807  Mehrquellenverarbeitung       90  ...         0  timeout
808  Mehrquellenverarbeitung       90  ...         0  timeout
809  Mehrquellenverarbeitung       90  ...         0      NaN

[810 rows x 11 columns]

In [29]:
df.groupby("task_type", as_index=False)["correct"].mean()

                   task_type   correct
0       Direkte Datenabfrage  0.751852
1  Einzelquellenverarbeitung  0.529630
2    Mehrquellenverarbeitung  0.462963

In [30]:
df.groupby("task_type", as_index=False)["efficient"].mean()

                   task_type  efficient
0       Direkte Datenabfrage   0.718519
1  Einzelquellenverarbeitung   0.440741
2    Mehrquellenverarbeitung   0.362963

In [42]:
df.groupby(["model", "task_type", "method"], as_index=False)["correct"].mean()

           model                  task_type         method   correct
0   gpt-5.4-mini       Direkte Datenabfrage  deterministic  0.800000
1   gpt-5.4-mini       Direkte Datenabfrage      iterative  0.666667
2   gpt-5.4-mini       Direkte Datenabfrage     plan-based  0.866667
3   gpt-5.4-mini  Einzelquellenverarbeitung  deterministic  0.766667
4   gpt-5.4-mini  Einzelquellenverarbeitung      iterative  0.466667
5   gpt-5.4-mini  Einzelquellenverarbeitung     plan-based  0.700000
6   gpt-5.4-mini    Mehrquellenverarbeitung  deterministic  0.933333
7   gpt-5.4-mini    Mehrquellenverarbeitung      iterative  0.533333
8   gpt-5.4-mini    Mehrquellenverarbeitung     plan-based  0.800000
9      qwen3:30b       Direkte Datenabfrage  deterministic  0.833333
10     qwen3:30b       Direkte Datenabfrage      iterative  0.866667
11     qwen3:30b       Direkte Datenabfrage     plan-based  0.500000
12     qwen3:30b  Einzelquellenverarbeitung  deterministic  0.633333
13     qwen3:30b  Einzelquellenverarbeitung      iterative  0.266667
14     qwen3:30b  Einzelquellenverarbeitung     plan-based  0.300000
15     qwen3:30b    Mehrquellenverarbeitung  deterministic  0.533333
16     qwen3:30b    Mehrquellenverarbeitung      iterative  0.066667
17     qwen3:30b    Mehrquellenverarbeitung     plan-based  0.100000
18      qwen3:8b       Direkte Datenabfrage  deterministic  0.733333
19      qwen3:8b       Direkte Datenabfrage      iterative  0.700000
20      qwen3:8b       Direkte Datenabfrage     plan-based  0.800000
21      qwen3:8b  Einzelquellenverarbeitung  deterministic  0.533333
22      qwen3:8b  Einzelquellenverarbeitung      iterative  0.366667
23      qwen3:8b  Einzelquellenverarbeitung     plan-based  0.733333
24      qwen3:8b    Mehrquellenverarbeitung  deterministic  0.700000
25      qwen3:8b    Mehrquellenverarbeitung      iterative  0.033333
26      qwen3:8b    Mehrquellenverarbeitung     plan-based  0.466667

In [44]:
df.groupby(["task_type", "method", "model"], as_index=False)[["correct", "efficient"]].mean()

                    task_type         method         model   correct  efficient
0        Direkte Datenabfrage  deterministic  gpt-5.4-mini  0.800000   0.733333
1        Direkte Datenabfrage  deterministic     qwen3:30b  0.833333   0.833333
2        Direkte Datenabfrage  deterministic      qwen3:8b  0.733333   0.733333
3        Direkte Datenabfrage      iterative  gpt-5.4-mini  0.666667   0.600000
4        Direkte Datenabfrage      iterative     qwen3:30b  0.866667   0.833333
5        Direkte Datenabfrage      iterative      qwen3:8b  0.700000   0.666667
6        Direkte Datenabfrage     plan-based  gpt-5.4-mini  0.866667   0.800000
7        Direkte Datenabfrage     plan-based     qwen3:30b  0.500000   0.466667
8        Direkte Datenabfrage     plan-based      qwen3:8b  0.800000   0.800000
9   Einzelquellenverarbeitung  deterministic  gpt-5.4-mini  0.766667   0.600000
10  Einzelquellenverarbeitung  deterministic     qwen3:30b  0.633333   0.600000
11  Einzelquellenverarbeitung  deterministic      qwen3:8b  0.533333   0.433333
12  Einzelquellenverarbeitung      iterative  gpt-5.4-mini  0.466667   0.366667
13  Einzelquellenverarbeitung      iterative     qwen3:30b  0.266667   0.266667
14  Einzelquellenverarbeitung      iterative      qwen3:8b  0.366667   0.300000
15  Einzelquellenverarbeitung     plan-based  gpt-5.4-mini  0.700000   0.500000
16  Einzelquellenverarbeitung     plan-based     qwen3:30b  0.300000   0.300000
17  Einzelquellenverarbeitung     plan-based      qwen3:8b  0.733333   0.600000
18    Mehrquellenverarbeitung  deterministic  gpt-5.4-mini  0.933333   0.766667
19    Mehrquellenverarbeitung  deterministic     qwen3:30b  0.533333   0.500000
20    Mehrquellenverarbeitung  deterministic      qwen3:8b  0.700000   0.666667
21    Mehrquellenverarbeitung      iterative  gpt-5.4-mini  0.533333   0.300000
22    Mehrquellenverarbeitung      iterative     qwen3:30b  0.066667   0.066667
23    Mehrquellenverarbeitung      iterative      qwen3:8b  0.033333   0.033333
24    Mehrquellenverarbeitung     plan-based  gpt-5.4-mini  0.800000   0.433333
25    Mehrquellenverarbeitung     plan-based     qwen3:30b  0.100000   0.100000
26    Mehrquellenverarbeitung     plan-based      qwen3:8b  0.466667   0.400000

In [34]:
timeout_ratio = (
    df.groupby(["task_type", "method"])["error"]
      .apply(lambda x: (x == "timeout").mean())
)

timeout_ratio

task_type                  method
Direkte Datenabfrage       deterministic    0.044444
                           iterative        0.100000
                           plan-based       0.188889
Einzelquellenverarbeitung  deterministic    0.155556
                           iterative        0.288889
                           plan-based       0.255556
Mehrquellenverarbeitung    deterministic    0.244444
                           iterative        0.533333
                           plan-based       0.433333
Name: error, dtype: float64